# Generated by Django 4.2 on 2023-04-15 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_zone_space_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash_can',
            name='space',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.space'),
        ),
    ]
