# Generated by Django 4.2 on 2023-04-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trash_can_space'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Residue',
        ),
    ]
