# Generated by Django 4.2 on 2023-05-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_space_updated_at_alter_trash_can_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
        migrations.AlterField(
            model_name='space',
            name='long',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
    ]
