# Generated by Django 4.2 on 2023-05-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_space_lat_alter_space_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='space',
            name='long',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
